name: FlashMiniGame
version: 1.0
description: Plugin de Mini jeux pour le serveur FlashBlock
author: Phunder
main: fr.phunder.flashminigame.Plugin
commands:
  ping:
    description: Cette command permet de tester la latence avec le serveur.
    usage: /ping
    permission: fmg.ping
    executor: fr.phunder.flashminigame.commands.CmdPing
  game:
    description: Cette command sers a la gestion des game.
    usage: /game help
    permission: fmg.game
    executor: fr.phunder.flashminigame.commands.CmdGame